### ISSUE TITLE
Error when methods are in-lined

### ISSUE THREAD

**Issue by Geraint87** [adamabdelhamed/PowerArgs#32]
I just found that when I build PowerArgs in release, I get a TargetInvocationException (and NullReferenceException inner exception) from the AttrOverride.cs Set method, at this line here:

``` C#
if (callingMethod.Name.StartsWith("set_") == false || callingMethod.IsSpecialName == false)
```

I have been told it's happening because:
- In the two lines above, it's using the StackTrace to find the calling member.
- It looks one frame ahead, and extracts the method name and tries to cast to MethodInfo

``` C#
StackTrace stackTrace = new StackTrace();
var callingMethod = stackTrace.GetFrame(1).GetMethod() as MethodInfo;
```
- What actually happens, is that the calling method has been optimised away by the compiler, and so what comes back from stackTrace.GetFrame(1).GetMethod() is in fact a RuntimeConstructorInfo, not method info.
- Then, it calls callingMethod.Name in the offending line, which throws a NullReferenceException

There are 7 references to this method, in CommandLineArgument.cs and CommandLineAction.cs

StackTrace is also used in the Get method of AttrOverride.cs but at the moment, it isn't being inlined (though the compiler is within its rights to at some point in the future!)

One workaround is to always build debug and release **without** optimisation.
![image](https://f.cloud.github.com/assets/5928208/1601393/494844ba-5387-11e3-91c7-6f820bee98fc.png)

Another is to decorate all of the calling members' sets like this:

``` C#
public string Description
{
    get
    {
        return overrides.Get<ArgDescription, string>(Metadata, d => d.Description, string.Empty);
    }
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    set
    {
        overrides.Set(value);
    }
}
```

With either of these methods, it runs fine.

What might be a better long-term solution is getting the name using CallerMemberName instead of stackTrace.GetFrame():
http://msdn.microsoft.com/en-us/library/system.runtime.compilerservices.callermembernameattribute(v=vs.110).aspx

(This is .Net 4.5 though)

**Comment by kenny-evitt** [comment]
I just ran into this when I added an 'arguments' class for a new action method for my CLI program.

I cloned the PowerArgs Git repo and built the Visual Studio solution successfully.

In the Visual Studio solution for my CLI program, I removed the PowerArgs NuGet package (the latest version on NuGet), and then added a copy of the PowerArgs build output assembly as a project reference.

I'm trying to run a Debug build of my CLI program.

The exceptions I'm observing do seem to be being thrown from a different location – `PowerArgs.CommandLineArgumentsDefinition.ValidateArguments(IEnumerable<CommandLineArgument> arguments)`.

Any ideas on I how I can workaround this?

I'm also happy to help debug this as well as submit a patch or PR if you can point me in the direction of a fix.

**Comment by adamabdelhamed** [comment]
The issue you've commented on was completely fixed.  The code no longer relies on a stack trace to do what it needs to do.

What specific error are you seeing?

**Comment by kenny-evitt** [comment]
@adamabdelhamed Here are the details of the exception that's being thrown now:

```
System.Reflection.TargetInvocationException was unhandled
  HResult=-2146232828
  Message=Exception has been thrown by the target of an invocation.
  Source=mscorlib
  StackTrace:
       at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
       at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
       at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
       at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
       at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
       at PowerArgs.CommandLineArgumentsDefinition.ValidateArguments(IEnumerable`1 arguments) in C:\@GitHub\PowerArgs\PowerArgs\ArgDefinition\CommandLineArgumentsDefinition.cs:line 672
       at PowerArgs.CommandLineArgumentsDefinition.Validate(HookContext context) in C:\@GitHub\PowerArgs\PowerArgs\ArgDefinition\CommandLineArgumentsDefinition.cs:line 543
       at PowerArgs.Args.ParseInternal(CommandLineArgumentsDefinition definition, String[] input) in C:\@GitHub\PowerArgs\PowerArgs\Args.cs:line 554
       at PowerArgs.Args.<>c__DisplayClass15_1.<InvokeAction>b__3() in C:\@GitHub\PowerArgs\PowerArgs\Args.cs:line 245
       at PowerArgs.Args.Execute[T](Func`1 argsProcessingCode) in C:\@GitHub\PowerArgs\PowerArgs\Args.cs:line 461
       at PowerArgs.Args.<>c__DisplayClass15_0.<InvokeAction>b__2(String[] a) in C:\@GitHub\PowerArgs\PowerArgs\Args.cs:line 242
       at PowerArgs.REPL.DriveREPL[T](TabCompletion t, Func`2 eval, String[] args) in C:\@GitHub\PowerArgs\PowerArgs\HelperTypesInternal\REPL.cs:line 28
       at PowerArgs.Args.InvokeAction(CommandLineArgumentsDefinition definition, String[] args) in C:\@GitHub\PowerArgs\PowerArgs\Args.cs:line 240
       at PowerArgs.Args.InvokeAction[T](String[] args) in C:\@GitHub\PowerArgs\PowerArgs\Args.cs:line 417
       at DbNecromancer.Cli.Program.Main(String[] args) in c:\@Kiln\DB Necromancer - CLI\DbNecromancer.Cli\Program.cs:line 18
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: System.NullReferenceException
       HResult=-2147467261
       Message=Object reference not set to an instance of an object.
       Source=PowerArgs
       StackTrace:
            at PowerArgs.AttrOverride.Get[T1,T2](String propertyName, IEnumerable`1 attriibutes, Func`2 getter, T2 defaultValue) in C:\@GitHub\PowerArgs\PowerArgs\HelperTypesInternal\AttrOverride.cs:line 50
            at PowerArgs.CommandLineArgument.get_DefaultValue() in C:\@GitHub\PowerArgs\PowerArgs\ArgDefinition\CommandLineArgument.cs:line 265
            at PowerArgs.CommandLineArgument.get_HasDefaultValue() in C:\@GitHub\PowerArgs\PowerArgs\ArgDefinition\CommandLineArgument.cs:line 254
       InnerException: 
```

I'm using the output of a local build of the *master* branch of this repo as-of Friday. I built the *Debug* configuration for the *Mixed Platforms* 'solution platform'.

[Here's the line that's throwing the exception.](https://github.com/adamabdelhamed/PowerArgs/blob/64cad497be8c67d9c37d106194492ffcc620633d/PowerArgs/ArgDefinition/CommandLineArgumentsDefinition.cs#L672)

**Comment by adamabdelhamed** [comment]
This appears to be a different issue than the one this thread was originally referring to.  

The line that actually throws is [this one](https://github.com/adamabdelhamed/PowerArgs/blob/64cad497be8c67d9c37d106194492ffcc620633d/PowerArgs/HelperTypesInternal/AttrOverride.cs#L50).  I **think** the only way that line can throw is if your application code tried to programatically override something like a description or default value property with a null.  That should not be allowed, and in an upcoming check in I'll throw sooner when that happens.  

I know I've been slow to respond (sorry), but can you recall if you did set an override to null somewhere? 

It would be something like `someArgument.Description = null;` where `someArgument` is of type `CommandLineArgumentDefinition`.

Thanks,
Adam

**Comment by kenny-evitt** [comment]
@adamabdelhamed Thanks for following-up! Unfortunately, I don't have a copy of the code for which the exception was being thrown. But that code very well may have been assigning `null` to the default value of one of the arguments.
