### ISSUE TITLE
Displaying usage in Powershell ISE raises an exception

### ISSUE THREAD

**Issue by Memesphere** [adamabdelhamed/PowerArgs#98]
I recently upgraded to Powerargs 2.6.0.1 (against .Net 4.0). I have noticed that displaying usage information in Powershell ISE now raises an exception where it doesn't in cmd or Powershell. 

A while back I raised a similar issue (https://github.com/adamabdelhamed/PowerArgs/issues/34) concerning interactive mode which was closed due to constraints on Powershell ISE support for the console class. However, at the time the usage feature of Powerargs still worked in Powershell ISE. This seems to have changed from 2.6.0.1

Here is the exception:
```
System.IO.IOException: The handle is invalid.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at System.Console.get_BufferWidth()
   at PowerArgs.ConsoleTableBuilder.DetermineColumnWidths(ConsoleTableBuilderContext context)
   at PowerArgs.ConsoleTableBuilder.FormatAsTable(List`1 columnHeaders, List`1 rows, String rowPrefix, List`1 columnOverflowBehaviors, Int32 gutter)
   at PowerArgs.TableExpression.Evaluate(DocumentRendererContext context)
   at PowerArgs.DocumentRenderer.Evaluate(List`1 expressions, DocumentRendererContext context)
   at PowerArgs.DocumentRenderer.Render(IEnumerable`1 tokens, DocumentRendererContext context)
   at PowerArgs.DocumentRendererContext.RenderBody(IEnumerable`1 body)
   at PowerArgs.IfExpression.Evaluate(DocumentRendererContext context)
   at PowerArgs.DocumentRenderer.Evaluate(List`1 expressions, DocumentRendererContext context)
   at PowerArgs.DocumentRenderer.Render(IEnumerable`1 tokens, DocumentRendererContext context)
   at PowerArgs.DocumentRendererContext.RenderBody(IEnumerable`1 body)
   at PowerArgs.IfExpression.Evaluate(DocumentRendererContext context)
   at PowerArgs.DocumentRenderer.Evaluate(List`1 expressions, DocumentRendererContext context)
   at PowerArgs.DocumentRenderer.Render(IEnumerable`1 tokens, DocumentRendererContext context)
   at PowerArgs.DocumentRendererContext.RenderBody(IEnumerable`1 body)
   at PowerArgs.IfExpression.Evaluate(DocumentRendererContext context)
   at PowerArgs.DocumentRenderer.Evaluate(List`1 expressions, DocumentRendererContext context)
   at PowerArgs.DocumentRenderer.Render(IEnumerable`1 tokens, DocumentRendererContext context)
   at PowerArgs.DocumentRenderer.Render(String template, DocumentRendererContext context, String sourceFileLocation)
   at PowerArgs.DocumentRenderer.Render(String template, Object data, String sourceFileLocation)
   at PowerArgs.ArgUsage.GenerateUsageFromTemplate(CommandLineArgumentsDefinition def, String template, String templateSourceLocation)
   at PowerArgs.UsageTemplateProvider.GetUsage(Type usageTemplateProviderType, CommandLineArgumentsDefinition definition)
   at PowerArgs.Args.DoStandardExceptionHandling[T](ArgException ex, HookContext context, CommandLineArgumentsDefinition definition)
   at PowerArgs.Args.Execute[T](Func`1 argsProcessingCode)
   at PowerArgs.Args.<>c__DisplayClassf.<InvokeAction>b__b(String[] a)
   at PowerArgs.REPL.DriveREPL[T](TabCompletion t, Func`2 eval, String[] args)
   at PowerArgs.Args.InvokeAction(CommandLineArgumentsDefinition definition, String[] args)
   at PowerArgs.Args.InvokeAction[T](String[] args)
   at TurfSport.BackOffice.Feed.Service.Console.PowerArgsStart(String[] args) in C:\svn\turfsport\TurfSportBackOffice\TurfSport4\trunk\TurfSport.BackOffice.Feed.Service\Console.cs:line 38
```

**Comment by adamabdelhamed** [comment]
I'll take a look soon

**Comment by adamabdelhamed** [comment]
The issue is that console apps can't access the width of the console from within the PowerShell ISE.  PowerArgs does this in a few places, including in the usage display so that it can be smart about wrapping long descriptions. 

I can fix this specific issue by assuming an 80 character console width in the case where the console throws an exception.  It won't look perfect (e.g. long descriptions may wrap conservatively), but it will work.

Sound good?

**Comment by Memesphere** [comment]
Sounds workable. It's certainly better than the current error dump on help.

Thanks for the quick response
Richard

Richard Dorman

**Comment by adamabdelhamed** [comment]
available in latest nuget package
